### ISSUE TITLE
Unable to train a TensorFlow Estimator locally

### ISSUE THREAD

**Issue by nectario** [aws/amazon-sagemaker-examples#1340]
I am trying to train a TensorFlow Estimator locally, but I get this issue:

Here is my code that I call:

```
from sagemaker.tensorflow import  TensorFlow

estimator = TensorFlow(entry_point="Testing.py",
                        role='SageMakerRole',
                        train_instance_count=1,
                        train_instance_type='local_gpu',
                        framework_version='2.2.0',
                        py_version='py37')
estimator.fit()

```

Testing.py is an empty script!

Please advise!

Thank you, 

Nektarios

"C:\Program Files\Python37\python.exe" C:/Development/Projects/DeepTradingAI/deeptradingmodels/DeepTradingEstimator.py
C:\Program Files\Python37\lib\site-packages\sagemaker\local\local_session.py:429: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(open(sagemaker_config_file, "r"))
Windows Support for Local Mode is Experimental
Legacy mode is deprecated in versions 1.13 and higher. Using script mode instead. Legacy mode and its training parameters will be deprecated in SageMaker Python SDK v2. Please use TF 1.13 or higher and script mode.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
WARNING! Using --password via the CLI is insecure. Use --password-stdin.

Creating tmpvy3d0546_algo-1-sk9mf_1 ... error
ERROR: for tmpvy3d0546_algo-1-sk9mf_1  Cannot create container for service algo-1-sk9mf: Unknown runtime specified nvidia

ERROR: for algo-1-sk9mf  Cannot create container for service algo-1-sk9mf: Unknown runtime specified nvidia
Encountered errors while bringing up the project.
Failed to delete: C:\Users\NEKTAR~1\AppData\Local\Temp\tmpvy3d0546\algo-1-sk9mf
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 161, in train
    _stream_output(process)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 677, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 166, in train
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', 'C:\\Users\\NEKTAR~1\\AppData\\Local\\Temp\\tmpvy3d0546\\docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Development/Projects/DeepTradingAI/deeptradingmodels/DeepTradingEstimator.py", line 11, in <module>
    estimator.fit()
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\tensorflow\estimator.py", line 483, in fit
    fit_super()
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\tensorflow\estimator.py", line 462, in fit_super
    super(TensorFlow, self).fit(inputs, wait, logs, job_name, experiment_config)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\estimator.py", line 494, in fit
    self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_config)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\estimator.py", line 1066, in start_new
    estimator.sagemaker_session.train(**train_args)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\session.py", line 590, in train
    self.sagemaker_client.create_training_job(**train_request)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\local_session.py", line 102, in create_training_job
    training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\entities.py", line 96, in start
    input_data_config, output_data_config, hyperparameters, job_name
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 174, in train
    self._cleanup(dirs_to_delete)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 597, in _cleanup
    _delete_tree(container_config_path)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 723, in _delete_tree
    shutil.rmtree(path)
  File "C:\Program Files\Python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Python37\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Program Files\Python37\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\NEKTAR~1\\AppData\\Local\\Temp\\tmpvy3d0546\\algo-1-sk9mf\\output'

**Comment by seanpmorgan** [comment]
Hi @nectario apologies for the slow response. There are a few things going on here. First as noted in the stack windows local mode is still experimental `Windows Support for Local Mode is Experimental` and may cause issues down the line.

Next, the error you're recieving appears to be due to not having nvidia-docker installed: `ERROR: for algo-1-sk9mf Cannot create container for service algo-1-sk9mf: Unknown runtime specified nvidia` 

This issue is a bit old, and recent docker releases have enabled the parameter `--gpus all` instead of having to install nvidia-docker. I'm going to close this because it's not related to any specific sagemaker example, but feel free to comment if this is still an issue for you and I can help investigate.
