### ISSUE TITLE
managed_spot_training_object_detection.ipynd fatal error in loading data

### ISSUE THREAD

**Issue by duane-edgington** [aws/amazon-sagemaker-examples#1612]
Hi. I am trying to walk through the 10-minute tutorial on Optimizing and Scaling Machine Learning Training. When I try to run my copy of the managed-spot_training_object_detection.ipynd notebook, following the tutorial steps exactly, I get a fatal error at Download and Prepare Data.
--2020-10-12 23:50:32--  http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... failed: No route to host.
--2020-10-12 23:50:35--  http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... failed: No route to host.
--2020-10-12 23:50:38--  http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... failed: No route to host.
tar: /tmp/VOCtrainval_11-May-2012.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: /tmp/VOCtrainval_06-Nov-2007.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: /tmp/VOCtest_06-Nov-2007.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "tools/prepare_dataset.py", line 95, in <module>
    db = load_pascal(args.set, args.year, args.root_path, args.shuffle)
  File "tools/prepare_dataset.py", line 63, in load_pascal
    imdbs.append(PascalVoc(s, y, devkit_path, shuffle, is_train=True))
  File "/home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/pascal_voc.py", line 59, in __init__
    self.image_set_index = self._load_image_set_index(shuffle)
  File "/home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/pascal_voc.py", line 91, in _load_image_set_index
    assert os.path.exists(image_set_index_file), 'Path does not exist: {}'.format(image_set_index_file)
AssertionError: Path does not exist: /home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/../VOCdevkit/VOC2007/ImageSets/Main/trainval.txt
Traceback (most recent call last):
  File "tools/prepare_dataset.py", line 95, in <module>
    db = load_pascal(args.set, args.year, args.root_path, args.shuffle)
  File "tools/prepare_dataset.py", line 63, in load_pascal
    imdbs.append(PascalVoc(s, y, devkit_path, shuffle, is_train=True))
  File "/home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/pascal_voc.py", line 59, in __init__
    self.image_set_index = self._load_image_set_index(shuffle)
  File "/home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/pascal_voc.py", line 91, in _load_image_set_index
    assert os.path.exists(image_set_index_file), 'Path does not exist: {}'.format(image_set_index_file)
AssertionError: Path does not exist: /home/ec2-user/SageMaker/managed_spot_training_object_detection_2020-10-12/tools/../VOCdevkit/VOC2007/ImageSets/Main/test.txt

I will go look at the data repository website to see if there is an update to the files, but in the meantime please check the notebook and correct the data download so us users can make progress.

Thank yoiu.

**Comment by duane-edgington** [comment]
I checked host.robots.ox.ac.uk and that site is not responding. Has been down for several days. I found an alternative mirror for the three data sets, and that worked.  http://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar  and the other two tar files as well. exactly the same names, and same size. I also found a mirror at Baidu but the file names were different (encapsulated in a zip file I believe). Anyway, it would be great if you could update the notebooks with working repositories, even better if they were within AWS.
