### ISSUE TITLE
scikit_bring_your_own.ipynb: Training job failed

### ISSUE THREAD

**Issue by yohei1126** [aws/amazon-sagemaker-examples#1618]
# Issue

* A trining job triggered by `amazon-sagemaker-examples/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb` failed to read input CSV file.
* `Exception during training: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
`

# procedure to reproduce the issue
* Run `amazon-sagemaker-examples/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb`
* You will get this error when it trigger a training job

```
2020-10-14 03:10:34 Starting - Starting the training job...
2020-10-14 03:10:36 Starting - Launching requested ML instances......
2020-10-14 03:11:36 Starting - Preparing the instances for training...
2020-10-14 03:12:14 Downloading - Downloading input data......
2020-10-14 03:13:35 Training - Training image download completed. Training in progress.
2020-10-14 03:13:35 Uploading - Uploading generated training model.Starting the training.
Exception during training: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
Traceback (most recent call last):
  File "/opt/program/train", line 48, in train
    raw_data = [ pd.read_csv(file, header=None) for file in input_files ]
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
```

## Error investigation

* Added `engine="python"` to `pd.read_csv` as the error message above suggsted

```
# raw_data = [ pd.read_csv(file, header=None) for file in input_files ]
    raw_data = [ pd.read_csv(file, header=None, engine="python") for file in input_files ]
```

* Tried it again, then I got this error.

```
2020-10-14 03:21:11 Starting - Starting the training job...
2020-10-14 03:21:13 Starting - Launching requested ML instances......
2020-10-14 03:22:13 Starting - Preparing the instances for training...
2020-10-14 03:22:58 Downloading - Downloading input data
2020-10-14 03:22:58 Training - Downloading the training image..Starting the training.
Exception during training: [Errno 21] Is a directory: '/opt/ml/input/data/training/model'
Traceback (most recent call last):
  File "/opt/program/train", line 49, in train
    raw_data = [ pd.read_csv(file, header=None, engine="python") for file in input_files ]
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1132, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 2225, in __init__
    memory_map=self.memory_map)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/common.py", line 421, in _get_handle
    f = open(path_or_buf, mode)
IOError: [Errno 21] Is a directory: '/opt/ml/input/data/training/model'
```

**Comment by yohei1126** [comment]
Sorry I messed up with S3 bucket location. That was the root cause.
