### ISSUE TITLE
UnexpectedStatusException: Error for Training job

### ISSUE THREAD

**Issue by muste1011** [aws/amazon-sagemaker-examples#1740]
Can you please quid me how to solve this error

UnexpectedStatusException: Error for Training job sagemaker-xgboost-2020-11-12-10-49-11-640: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_algorithm_toolkit/hyperparameter_validation.py", line 278, in validate
    hyperparameter_obj = self.hyperparameters[hp]
KeyError: 'silent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 94, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 90, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 68, in run_algorithm_mode
    checkpoint_config=checkpoint_config
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/algorithm_mode/train.

**Comment by paul-cb** [comment]
Hi @muste1011, what version of XGBoost are you using?

**Comment by muste1011** [comment]
Hello @paul-cb , I am using Version 1.2-1

**Comment by hitchingsh** [comment]
I just ran into that same error in the Amazon SageMaker Getting Started Tutorial but fixed it by removing the silent parameter from xgb_model.set_hyperparameters( on this page: https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-train-model.html

I was using the Amazon SageMaker Python example not the Boto3.  I recommend Amazon update their documentation.

**Comment by paul-cb** [comment]
@muste1011 Are you using boto3 or Python SDK?

**Comment by paul-cb** [comment]
No Activity. Closing.

**Comment by MahmadSharaf** [comment]
I have the exact same error. And I am running this on my local laptop using Python SDK

SageMaker SDK version: `sagemaker==2.23.4.post0`.
XGBoost version: `container = sagemaker.image_uris.retrieve("xgboost", "us-east-1","1.2-1")`
XGB-Hyperparameters:
```
xgb.set_hyperparameters(max_depth=5, 
                        eta=0.2, 
                        gamma=4,
                        min_child_weight=6, 
                        subsample=0.8, 
                        silent=1,
                        objective='binary:logistic', 
                        num_round=100)
```
Model Fitting command: `xgb.fit({'train': s3_input_train, 'validation': s3_input_validation})`

Model Training History:
```txt
2021-01-16 08:54:39 Starting - Starting the training job...
2021-01-16 08:55:02 Starting - Launching requested ML instancesProfilerReport-1610787312: InProgress
......
2021-01-16 08:56:11 Starting - Preparing the instances for training.........
2021-01-16 08:58:04 Downloading - Downloading input data
2021-01-16 08:58:04 Training - Downloading the training image...
2021-01-16 08:58:47 Uploading - Uploading generated training model
2021-01-16 08:58:47 Failed - Training job failed
```

Model Training Error:
```
UnexpectedStatusException: Error for Training job sagemaker-xgboost-2021-01-16-08-55-12-072: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_algorithm_toolkit/hyperparameter_validation.py", line 278, in validate
    hyperparameter_obj = self.hyperparameters[hp]
KeyError: 'silent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 94, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 90, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 68, in run_algorithm_mode
    checkpoint_config=checkpoint_config
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/algorithm_mode/train.
```

**Comment by phoenixrishabh** [comment]
Just commented out the silent parameter and it worked for me.

**Comment by RahulJana** [comment]
I am Facing a similar type of error.
Model Training Error Log:
`INFO:sagemaker:Creating training-job with name: rf-scikit-2023-09-28-07-37-56-820
Using provided s3_resource
2023-09-28 07:37:57 Starting - Starting the training job...
2023-09-28 07:38:12 Starting - Preparing the instances for training......
2023-09-28 07:39:14 Downloading - Downloading input data......
2023-09-28 07:40:04 Training - Downloading the training image..2023-09-28 07:40:38,821 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training
2023-09-28 07:40:38,826 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2023-09-28 07:40:38,875 sagemaker_sklearn_container.training INFO     Invoking user training script.
2023-09-28 07:40:39,036 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2023-09-28 07:40:39,049 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2023-09-28 07:40:39,062 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2023-09-28 07:40:39,071 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "test": "/opt/ml/input/data/test",
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_sklearn_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "max-leaf-nodes": 3,
        "n-estimators": 100
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "test": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        },
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "is_master": true,
    "job_name": "rf-scikit-2023-09-28-07-37-56-820",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-975048338421/rf-scikit-2023-09-28-07-37-56-820/source/sourcedir.tar.gz",
    "module_name": "script_updated",
    "network_interface_name": "eth0",
    "num_cpus": 2,
    "num_gpus": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.m5.large",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.m5.large",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0"
    },
    "user_entry_point": "script_updated.py"
}
Environment variables:
SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"max-leaf-nodes":3,"n-estimators":100}
SM_USER_ENTRY_POINT=script_updated.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={"test":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["test","train"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=script_updated
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_sklearn_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=2
SM_NUM_GPUS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-975048338421/rf-scikit-2023-09-28-07-37-56-820/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"test":"/opt/ml/input/data/test","train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_sklearn_container.training:main","hosts":["algo-1"],"hyperparameters":{"max-leaf-nodes":3,"n-estimators":100},"input_config_dir":"/opt/ml/input/config","input_data_config":{"test":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"rf-scikit-2023-09-28-07-37-56-820","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-975048338421/rf-scikit-2023-09-28-07-37-56-820/source/sourcedir.tar.gz","module_name":"script_updated","network_interface_name":"eth0","num_cpus":2,"num_gpus":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0"},"user_entry_point":"script_updated.py"}
SM_USER_ARGS=["--max-leaf-nodes","3","--n-estimators","100"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TEST=/opt/ml/input/data/test
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_HP_MAX-LEAF-NODES=3
SM_HP_N-ESTIMATORS=100
PYTHONPATH=/opt/ml/code:/miniconda3/bin:/miniconda3/lib/python37.zip:/miniconda3/lib/python3.7:/miniconda3/lib/python3.7/lib-dynload:/miniconda3/lib/python3.7/site-packages
Invoking script with the following command:
/miniconda3/bin/python script_updated.py --max-leaf-nodes 3 --n-estimators 100
extracting arguments
reading data
Traceback (most recent call last):
  File "script_updated.py", line 44, in <module>
    train_df = pd.read_csv(os.path.join(args.train, args.train_file))
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/train/train.csv'
2023-09-28 07:40:40,091 sagemaker-containers ERROR    Reporting training FAILURE
2023-09-28 07:40:40,091 sagemaker-containers ERROR    framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 39, in main
    train(environment.Environment())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 35, in train
    runner_type=runner.ProcessRunnerType)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py", line 100, in run
    wait, capture_error
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 291, in run
    cwd=environment.code_dir,
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 208, in check_error
    info=extra_info,
sagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/miniconda3/bin/python script_updated.py --max-leaf-nodes 3 --n-estimators 100"
ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/miniconda3/bin/python script_updated.py --max-leaf-nodes 3 --n-estimators 100"

2023-09-28 07:40:57 Uploading - Uploading generated training model
2023-09-28 07:40:57 Failed - Training job failed`

Error Message:
`
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
Cell In[15], line 2
      1 # launch training job, with asynchronous call
----> 2 sklearn_estimator.fit({"train": train_path, "test": test_path}, wait=True)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/workflow/pipeline_context.py:311, in runnable_by_pipeline.<locals>.wrapper(*args, **kwargs)
    307         return context
    309     return _StepArguments(retrieve_caller_name(self_instance), run_func, *args, **kwargs)
--> 311 return run_func(*args, **kwargs)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/estimator.py:1310, in EstimatorBase.fit(self, inputs, wait, logs, job_name, experiment_config)
   1308 self.jobs.append(self.latest_training_job)
   1309 if wait:
-> 1310     self.latest_training_job.wait(logs=logs)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/estimator.py:2580, in _TrainingJob.wait(self, logs)
   2578 # If logs are requested, call logs_for_jobs.
   2579 if logs != "None":
-> 2580     self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   2581 else:
   2582     self.sagemaker_session.wait_for_job(self.job_name)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:4849, in Session.logs_for_job(self, job_name, wait, poll, log_type, timeout)
   4828 def logs_for_job(self, job_name, wait=False, poll=10, log_type="All", timeout=None):
   4829     """Display logs for a given training job, optionally tailing them until job is complete.
   4830 
   4831     If the output is a tty or a Jupyter cell, it will be color-coded
   (...)
   4847         exceptions.UnexpectedStatusException: If waiting and the training job fails.
   4848     """
-> 4849     _logs_for_job(self.boto_session, job_name, wait, poll, log_type, timeout)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:6760, in _logs_for_job(boto_session, job_name, wait, poll, log_type, timeout)
   6757             last_profiler_rule_statuses = profiler_rule_statuses
   6759 if wait:
-> 6760     _check_job_status(job_name, description, "TrainingJobStatus")
   6761     if dot:
   6762         print()

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:6813, in _check_job_status(job, desc, status_key_name)
   6807 if "CapacityError" in str(reason):
   6808     raise exceptions.CapacityError(
   6809         message=message,
   6810         allowed_statuses=["Completed", "Stopped"],
   6811         actual_status=status,
   6812     )
-> 6813 raise exceptions.UnexpectedStatusException(
   6814     message=message,
   6815     allowed_statuses=["Completed", "Stopped"],
   6816     actual_status=status,
   6817 )

UnexpectedStatusException: Error for Training job rf-scikit-2023-09-28-07-37-56-820: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 39, in main
    train(environment.Environment())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 35, in train
    runner_type=runner.ProcessRunnerType)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py", line 100, in run
    wait, capture_error
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 291, in run
    cwd=environment.code_dir,
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 208, in check_error
    info=extra_info,
sagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/miniconda3/bin/python script_updated.py --max-leaf-nod
`

Training parameters:
`
sklearn_estimator = SKLearn(
    entry_point='script_updated.py',
    role=ROLE,
    instance_count=1,
    instance_type='ml.m5.large',
    framework_version="0.23-1",
    base_job_name='rf-scikit',
    hyperparameters={'n-estimators': 100,
                     'max-leaf-nodes': 3})
`

Sagemaker version: `'2.183.0'`
