### ISSUE TITLE
Unable to get predictions from SageMaker local endpoint

### ISSUE THREAD

**Issue by 1pyroaqua** [aws/amazon-sagemaker-examples#1886]
Hello All-

I'm new to using SageMaker and I'm struggling to get a local endpoint working. Below is my code, followed by the error 

**Project Folder structure:**

```console
/
|
|__container
    |__code
        |__train.py
        |__requirements.txt
    |__Dockerfile
|__notebook.ipynb
|__build_and_push.sh
```

**train.py**
```python
import os
import warnings
import sys
import json
import ast
import argparse
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import PolynomialFeatures
from urllib.parse import urlparse
import logging
import pickle

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2

if __name__ =='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model-dir', type=str, default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--train', type=str, default=os.environ.get('SM_CHANNEL_TRAIN'))
    parser.add_argument('--test', type=str, default=os.environ.get('SM_CHANNEL_TEST'))
    parser.add_argument('--train-file', type=str, default='kc_house_data_train.csv')
    parser.add_argument('--test-file', type=str, default='kc_house_data_test.csv')
    parser.add_argument('--features', type=str)  
    parser.add_argument('--target', type=str) 

    args, _ = parser.parse_known_args()

    warnings.filterwarnings("ignore")
    np.random.seed(40)

    # Reading training and testing datasets
    logging.info('reading training and testing datasets')
    train_df = pd.read_csv(os.path.join(args.train, args.train_file))
    test_df = pd.read_csv(os.path.join(args.test, args.test_file))
    train_x = np.array(train_df[args.features.split(',')]).reshape(-1,1)
    test_x = np.array(test_df[args.features.split(',')]).reshape(-1,1)
    train_y = np.array(train_df[args.target]).reshape(-1,1)
    test_y = np.array(test_df[args.target]).reshape(-1,1)
     
     reg=linear_model.LinearRegression()
     reg.fit(train_x, train_y)

     predicted = reg.predict(test_x)

     (rmse, mae, r2) = eval_metrics(test_y, predicted)
        
      # Logging parameters and metric to mlflow as well as logger
      logging.info(f"        Linear model: (features={args.features}, target={args.target})")
      logging.info(f"            RMSE: {rmse}")
      logging.info(f"            MAE: {mae}")
      logging.info(f"            R2: {r2}")
      logging.info(f"    Tags: {args.tags}") 

      # Save model
      model_path = os.path.join(args.model_dir, "model.pkl")
      logging.info(f"saving to {model_path}")
      with open(model_path, 'wb') as path:
          pickle.dump(reg, path)

def model_fn(model_dir):
    with open(os.path.join(model_dir, "model.pkl"), "rb") as input_model:
        model = pickle.load(input_model)
    return model
    
def predict_fn(data, model):
    return model.predict(data)
```

**notebook**
```python
image_uri = '8345678891234.dkr.ecr.us-east-1.amazonaws.com/sagemaker-test:latest'
___

hyperparameters = {
    'features': 'sqft_living',
    'target': 'price'
    }
local_mode = True
___

Estimator = sm.estimator.Estimator

estimator = Estimator(
    role = sm_role,
    train_instance_count = 1,
    train_instance_type = 'local' if local_mode else 'ml.m5.large',
    image_name = image_uri,
    base_job_name = 'housing-price-prediction',
    hyperparameters = hyperparameters,
    subnets=['subnet-b88aa077', 
             'subnet-u45673d1'],
    security_group_ids=['sg-c08b6532']
    
)   
___

estimator.fit(
    {'train':'s3://sagemaker-us-east-1-1234567/housing-price-prediction/curated/train', 
     'test':'s3://sagemaker-us-east-1-1234567/housing-price-prediction/curated/test'},
     wait=False,
     logs=True)

___
predictor = estimator.deploy(instance_type='local' if local_mode else 'ml.t2.medium',
                 initial_instance_count=1)   

___
test_data = pd.read_csv("s3://sagemaker-us-east-1-1234567/housing-price-prediction/curated/predict/kc_house_data_predict.csv")
get_prediction=np.array(test_data['sqft_living']).reshape(-1,1)

predictor.predict(data=get_prediction)

## Once I run the predictor.predict, I get the following error

```
**Error Traceback**
```console
algo-1-3141y_1  | 2020-12-24 21:20:16,802 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
algo-1-3141y_1  | 2020-12-24 21:20:17,625 INFO - root - /opt/ml/model
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
algo-1-3141y_1  | 2020-12-24 21:20:17,629 ERROR - train - Exception on /invocations [POST]
algo-1-3141y_1  | Traceback (most recent call last):
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
algo-1-3141y_1  |     return fn(*args, **kwargs)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 59, in default_input_fn
algo-1-3141y_1  |     np_array = encoders.decode(input_data, content_type)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_encoders.py", line 211, in decode
algo-1-3141y_1  |     return decoder(obj)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_encoders.py", line 97, in json_to_numpy
algo-1-3141y_1  |     data = json.loads(string_like)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
algo-1-3141y_1  |     return _default_decoder.decode(s)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
algo-1-3141y_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
algo-1-3141y_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
algo-1-3141y_1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
algo-1-3141y_1  | 
algo-1-3141y_1  | During handling of the above exception, another exception occurred:
algo-1-3141y_1  | 
algo-1-3141y_1  | Traceback (most recent call last):
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
algo-1-3141y_1  |     response = self.full_dispatch_request()
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
algo-1-3141y_1  |     rv = self.handle_user_exception(e)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
algo-1-3141y_1  |     reraise(exc_type, exc_value, tb)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
algo-1-3141y_1  |     raise value
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
algo-1-3141y_1  |     rv = self.dispatch_request()
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
algo-1-3141y_1  |     return self.view_functions[rule.endpoint](**req.view_args)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 200, in transform
algo-1-3141y_1  |     self._model, request.content, request.content_type, request.accept
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 227, in _default_transform_fn
algo-1-3141y_1  |     data = self._input_fn(content, content_type)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 95, in wrapper
algo-1-3141y_1  |     six.reraise(error_class, error_class(e), sys.exc_info()[2])
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
algo-1-3141y_1  |     raise value.with_traceback(tb)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
algo-1-3141y_1  |     return fn(*args, **kwargs)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 59, in default_input_fn
algo-1-3141y_1  |     np_array = encoders.decode(input_data, content_type)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_encoders.py", line 211, in decode
algo-1-3141y_1  |     return decoder(obj)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_encoders.py", line 97, in json_to_numpy
algo-1-3141y_1  |     data = json.loads(string_like)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
algo-1-3141y_1  |     return _default_decoder.decode(s)
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
algo-1-3141y_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
algo-1-3141y_1  |   File "/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
algo-1-3141y_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
algo-1-3141y_1  | sagemaker_containers._errors.ClientError: Expecting value: line 1 column 1 (char 0)
algo-1-3141y_1  | 172.18.0.1 - - [24/Dec/2020:21:20:17 +0000] "POST /invocations HTTP/1.1" 500 290 "-" "-"
```

**Comment by 1pyroaqua** [comment]
Any thoughts anyone?

**Comment by hsl89** [comment]
hi @1pyroaqua , try here https://stackoverflow.com/questions/tagged/amazon-sagemaker
