### ISSUE TITLE
Unable to load Compiled model in GreenGrass

### ISSUE THREAD

**Issue by thasin96** [aws/amazon-sagemaker-examples#1915]
GreenGrass Version: 1.11.0
Edge Device: Jetson Nano
Cuda Version: 10.0
TensorRt Version: 5.1.6

I have compiled a model using neo. Using this model, I am able to perform inference properly. Now, I want to integrate GG to auto deployment. I am able to deploy the model. But when lambda starts loading model from my configured directory, it throws TVM error. Below is the stacktrace:
```
[2021-01-06T13:38:36.025+05:30][ERROR]-__init__.py:1028,2021-01-06 13:38:35,895 INFO Found libdlr.so in model artifact. Using dlr from /trained_model/libdlr.so
[2021-01-06T13:38:36.049+05:30][ERROR]-__init__.py:1028,2021-01-06 13:38:35,895 INFO Found libdlr.so in model artifact. Using dlr from /trained_model/libdlr.so
[2021-01-06T13:38:36.211+05:30][ERROR]-NvRmPrivGetChipIdLimited: Could not read Tegra chip id/rev 
[2021-01-06T13:38:36.211+05:30][ERROR]-Expected on kernels without fuse support, using Tegra K1
[2021-01-06T13:38:36.211+05:30][ERROR]-NvRmPrivGetChipPlatform: Could not read platform information 
[2021-01-06T13:38:36.211+05:30][ERROR]-Expected on kernels without fuse support, using silicon
[2021-01-06T13:38:36.212+05:30][ERROR]-libnvrm_gpu.so: NvRmGpuLibOpen failed
[2021-01-06T13:38:36.221+05:30][ERROR]-[13:38:36] /home/nvidia/neo-ai-dlr/src/dlr.cc:326: [13:38:36] /home/nvidia/neo-ai-dlr/3rdparty/tvm/src/runtime/cuda/cuda_device_api.cc:115: 
[2021-01-06T13:38:36.221+05:30][ERROR]----------------------------------------------------------------
[2021-01-06T13:38:36.221+05:30][ERROR]-An internal invariant was violated during the execution of TVM.
[2021-01-06T13:38:36.221+05:30][ERROR]-Please read TVM's error reporting guidelines.
[2021-01-06T13:38:36.221+05:30][ERROR]-More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
[2021-01-06T13:38:36.221+05:30][ERROR]----------------------------------------------------------------
[2021-01-06T13:38:36.221+05:30][ERROR]-  Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading == false: CUDA: unknown error
[2021-01-06T13:38:36.221+05:30][ERROR]-Stack trace:
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (0) /trained_model/libdlr.so(+0xf82d8) [0x7fac06b2d8]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (1) /trained_model/libdlr.so(tvm::runtime::CUDADeviceAPI::AllocDataSpace(DLContext, unsigned long, unsigned long, DLDataType)+0x228) [0x7fac06f818]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (2) /trained_model/libdlr.so(+0x23d0c0) [0x7fac1b00c0]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (3) /trained_model/libdlr.so(+0x27b7e4) [0x7fac1ee7e4]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (4) /trained_model/libdlr.so(+0x27ce44) [0x7fac1efe44]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (5) /trained_model/libdlr.so(dlr::TVMModel::SetupTVMModule(std::vector<ModelElem, std::allocator<ModelElem> > const&)+0x3c8) [0x7fac064b50]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (6) /trained_model/libdlr.so(dlr::TVMModel::SetupTVMModule(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x174) [0x7fac066ae4]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (7) /trained_model/libdlr.so(CreateDLRModel+0x2ec) [0x7fac01a9ac]
[2021-01-06T13:38:36.221+05:30][ERROR]-  [bt] (8) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7fad1e3d28]
[2021-01-06T13:38:36.249+05:30][ERROR]-__init__.py:1028,2021-01-06 13:38:36,221 ERROR error in DLRModel instantiation 
[2021-01-06T13:38:36.249+05:30][ERROR]-Traceback (most recent call last):
[2021-01-06T13:38:36.249+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/api.py", line 100, in __init__
[2021-01-06T13:38:36.249+05:30][ERROR]-    self._impl = DLRModelImpl(model_path, dev_type, dev_id, error_log_file, use_default_dlr)
[2021-01-06T13:38:36.249+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/dlr_model.py", line 106, in __init__
[2021-01-06T13:38:36.249+05:30][ERROR]-    c_int(dev_id)))
[2021-01-06T13:38:36.249+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/dlr_model.py", line 184, in _check_call
[2021-01-06T13:38:36.249+05:30][ERROR]-    raise DLRError(self._lib.DLRGetLastError().decode('ascii'))
[2021-01-06T13:38:36.249+05:30][ERROR]-dlr.dlr_model.DLRError
[2021-01-06T13:38:36.274+05:30][ERROR]-__init__.py:1028,2021-01-06 13:38:36,221 ERROR error in DLRModel instantiation 
[2021-01-06T13:38:36.274+05:30][ERROR]-Traceback (most recent call last):
[2021-01-06T13:38:36.274+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/api.py", line 100, in __init__
[2021-01-06T13:38:36.274+05:30][ERROR]-    self._impl = DLRModelImpl(model_path, dev_type, dev_id, error_log_file, use_default_dlr)
[2021-01-06T13:38:36.274+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/dlr_model.py", line 106, in __init__
[2021-01-06T13:38:36.274+05:30][ERROR]-    c_int(dev_id)))
[2021-01-06T13:38:36.274+05:30][ERROR]-  File "/usr/local/lib/python3.7/dist-packages/dlr/dlr_model.py", line 184, in _check_call
[2021-01-06T13:38:36.274+05:30][ERROR]-    raise DLRError(self._lib.DLRGetLastError().decode('ascii'))
[2021-01-06T13:38:36.274+05:30][ERROR]-dlr.dlr_model.DLRError
[2021-01-06T13:38:36.274+05:30][FATAL]-lambda_runtime.py:142,Failed to import handler function "lambda_function.lambda_handler" due to exception: 
[2021-01-06T13:38:36.274+05:30][FATAL]-lambda_runtime.py:382,Failed to initialize Lambda runtime due to exception: 
[2021-01-06T13:38:37.691+05:30][ERROR]-__init__.py:1028,2021-01-06 13:38:37,565 INFO Found libdlr.so in model artifact. Using dlr from /trained_model/libdlr.so
```
I am not sure why it didn't work. Any hint would be appreciable. If you need any further details, please let me know.

**Comment by hsl89** [comment]
Hi @thasin96 , please post the question here https://stackoverflow.com/questions/tagged/amazon-sagemaker
