### ISSUE TITLE
Sagemaker Pipelines example -An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by YingUK** [aws/amazon-sagemaker-examples#1923]
Hi, 

I followed instructions from example step by step: https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-pipelines/tabular/customizing_build_train_deploy_project/sagemaker-pipelines-customized-project.ipynb
codebuild was successful, but failed when running the pipeline. Error shows as: 
`botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`

I added S3 bucket and object permissions for the sagemaker execution role I'm using.  could you suggest how to fix this please?

**Comment by seanpmorgan** [comment]
Hi @YingUK would you mind elaborating on when you get this error and the full trace stack to help us troubleshoot?

If I were to guess you may have missed the step where you need to update the `default_value` for the parameter string `InputDataUrl` inside of `modelbuild.pipelines.customer_churn.pipeline.py`.

This:
```
input_data = ParameterString(
    name="InputDataUrl",
    default_value=f"s3://sm-pipelines-demo-data-123456789/churn.txt",  # Change this to point to the s3 location of your raw input data.
)
```

Needs to be changed to the bucket where you uploaded the dataset in a separate notebook. If this is your issue let us know and we can edit the notebook to make this more clear.

**Comment by houying-aws** [comment]
Hi @seanpmorgan, thanks for your reply. Please see the full logs below. I did change the s3 path, it can be seen from below logs as well. 
```
1610093575459 | [ 2021-01-08T08:12:55.459Z ] Traceback (most recent call last): File "/opt/ml/processing/input/code/preprocess.py", line 42, in <module> s3.Bucket(bucket).download_file(key, fn) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file ExtraArgs=ExtraArgs, Callback=Callback, Config=Config) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 172, in download_file extra_args=ExtraArgs, callback=Callback) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file future.result() File "/miniconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result return self._coordinator.result() File "/miniconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result raise self._exception File "/miniconda3/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main self._submit(transfer_future=transfer_future, **kwargs) File "/miniconda3/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit **transfer_future.meta.call_args.extra_args File "/miniconda3/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call return self._make_api_call(operation_name, kwargs) File "/miniconda3/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call raise error_class(parsed_response, operation_name)

1610093575459 | [ 2021-01-08T08:12:55.459Z ] IMDS ENDPOINT: http://169.254.169.254/

1610093575459 | [ 2021-01-08T08:12:55.459Z ] Downloading data from bucket: project-jan-2021, key: pipeline-example/data/RawData.csv

1610093575459 | [ 2021-01-08T08:12:55.459Z ] s3://project-jan-2021/pipeline-example/data/RawData.csv

1610093575459 | [ 2021-01-08T08:12:55.459Z ] Starting preprocessing.
```

Many thanks,

**Comment by YingUK** [comment]
Hi @seanpmorgan, thanks for your reply. Please see the full logs below. I did change the s3 path, it can be seen from below logs as well. 
```
1610093575459 | [ 2021-01-08T08:12:55.459Z ] Traceback (most recent call last): File "/opt/ml/processing/input/code/preprocess.py", line 42, in <module> s3.Bucket(bucket).download_file(key, fn) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file ExtraArgs=ExtraArgs, Callback=Callback, Config=Config) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 172, in download_file extra_args=ExtraArgs, callback=Callback) File "/miniconda3/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file future.result() File "/miniconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result return self._coordinator.result() File "/miniconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result raise self._exception File "/miniconda3/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main self._submit(transfer_future=transfer_future, **kwargs) File "/miniconda3/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit **transfer_future.meta.call_args.extra_args File "/miniconda3/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call return self._make_api_call(operation_name, kwargs) File "/miniconda3/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call raise error_class(parsed_response, operation_name)

1610093575459 | [ 2021-01-08T08:12:55.459Z ] IMDS ENDPOINT: http://169.254.169.254/

1610093575459 | [ 2021-01-08T08:12:55.459Z ] Downloading data from bucket: project-jan-2021, key: pipeline-example/data/RawData.csv

1610093575459 | [ 2021-01-08T08:12:55.459Z ] s3://project-jan-2021/pipeline-example/data/RawData.csv

1610093575459 | [ 2021-01-08T08:12:55.459Z ] Starting preprocessing.
```

Many thanks,

**Comment by heming611** [comment]
Thank you, houying-aws, I added `/*` after <BUCKET_NAME> in order for AmazonSageMakerServiceCatalogProductsUseRole to access all the files under that bucket, and it worked.
