### ISSUE TITLE
[Bug Report] SageMaker Distributed Data Parallel - PyTorch with MNIST example notebook breaks

### ISSUE THREAD

**Issue by mchoi8739** [aws/amazon-sagemaker-examples#2044]
**Link to the notebook**
https://github.com/aws/amazon-sagemaker-examples/blob/master/training/distributed_training/pytorch/data_parallel/mnist/pytorch_smdataparallel_mnist_demo.ipynb

**Describe the bug**
The training job fails with the following log:
```
2021-03-03 16:59:56 Starting - Starting the training job...
2021-03-03 17:00:22 Starting - Launching requested ML instancesProfilerReport-1614790795: InProgress
............
2021-03-03 17:02:24 Starting - Preparing the instances for training............
2021-03-03 17:04:25 Downloading - Downloading input data...
2021-03-03 17:04:45 Training - Downloading the training image.........
2021-03-03 17:06:28 Training - Training image download completed. Training in progress.bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-03-03 17:06:17,205 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2021-03-03 17:06:17,283 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-03-03 17:06:28,819 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2021-03-03 17:06:28,896 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2021-03-03 17:06:35,126 sagemaker_pytorch_container.training INFO     Invoking SMDataParallel
2021-03-03 17:06:35,127 sagemaker_pytorch_container.training INFO     Invoking user training script.
2021-03-03 17:06:35,745 sagemaker-training-toolkit INFO     Starting MPI run as worker node.
2021-03-03 17:06:35,745 sagemaker-training-toolkit INFO     Waiting for MPI Master to create SSH daemon.
2021-03-03 17:06:35,747 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:35,747 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:36,749 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:36,749 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:37,750 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:37,751 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:38,753 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:38,753 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:39,755 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:39,755 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:40,757 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:40,757 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:41,758 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:41,759 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:42,725 sagemaker_pytorch_container.training INFO     Invoking SMDataParallel
2021-03-03 17:06:42,725 sagemaker_pytorch_container.training INFO     Invoking user training script.
2021-03-03 17:06:42,760 sagemaker-training-toolkit INFO     Cannot connect to host algo-1
2021-03-03 17:06:42,760 sagemaker-training-toolkit INFO     Connection failed with exception: 
 [Errno None] Unable to connect to port 22 on 10.2.127.193
2021-03-03 17:06:43,327 sagemaker-training-toolkit INFO     Starting MPI run as worker node.
2021-03-03 17:06:43,327 sagemaker-training-toolkit INFO     Creating SSH daemon.
2021-03-03 17:06:43,330 sagemaker-training-toolkit INFO     Waiting for MPI workers to establish their SSH connections
2021-03-03 17:06:43,332 sagemaker-training-toolkit INFO     Cannot connect to host algo-2 at port 22
2021-03-03 17:06:43,332 sagemaker-training-toolkit ERROR    Connection failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_training/smdataparallel.py", line 306, in _can_connect
    client.connect(host, port=port)
  File "/opt/conda/lib/python3.6/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.2.107.0
2021-03-03 17:06:43,335 sagemaker-training-toolkit INFO     Connection closed
2021-03-03 17:06:43,769 paramiko.transport INFO     Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-03 17:06:43,840 paramiko.transport INFO     Authentication (publickey) successful!
2021-03-03 17:06:43,840 sagemaker-training-toolkit INFO     Can connect to host algo-1
2021-03-03 17:06:43,840 sagemaker-training-toolkit INFO     MPI Master online, creating SSH daemon.
2021-03-03 17:06:43,840 sagemaker-training-toolkit INFO     Writing environment variables to /etc/environment for the MPI process.
2021-03-03 17:06:43,844 sagemaker-training-toolkit INFO     Waiting for MPI process to finish.
2021-03-03 17:06:44,343 paramiko.transport INFO     Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-03 17:06:44,412 paramiko.transport INFO     Authentication (publickey) successful!
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     Can connect to host algo-2 at port 22
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     Connection closed
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     Worker algo-2 available for communication
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     Network interface name: eth0
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     Host: ['algo-1', 'algo-2']
2021-03-03 17:06:44,413 sagemaker-training-toolkit INFO     instance type: ml.p3.16xlarge
2021-03-03 17:06:44,492 sagemaker-training-toolkit INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {
        "sagemaker_distributed_dataparallel_enabled": true,
        "sagemaker_instance_type": "ml.p3.16xlarge"
    },
    "channel_input_dirs": {},
    "current_host": "algo-1",
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1",
        "algo-2"
    ],
    "hyperparameters": {},
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {},
    "input_dir": "/opt/ml/input",
    "is_master": true,
    "job_name": "pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1/pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429/source/sourcedir.tar.gz",
    "module_name": "train_pytorch_smdataparallel_mnist",
    "network_interface_name": "eth0",
    "num_cpus": 64,
    "num_gpus": 8,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "hosts": [
            "algo-1",
            "algo-2"
        ],
        "network_interface_name": "eth0"
    },
    "user_entry_point": "train_pytorch_smdataparallel_mnist.py"
}

Environment variables:

SM_HOSTS=["algo-1","algo-2"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={}
SM_USER_ENTRY_POINT=train_pytorch_smdataparallel_mnist.py
SM_FRAMEWORK_PARAMS={"sagemaker_distributed_dataparallel_enabled":true,"sagemaker_instance_type":"ml.p3.16xlarge"}
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=[]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=train_pytorch_smdataparallel_mnist
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=64
SM_NUM_GPUS=8
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1/pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{"sagemaker_distributed_dataparallel_enabled":true,"sagemaker_instance_type":"ml.p3.16xlarge"},"channel_input_dirs":{},"current_host":"algo-1","framework_module":"sagemaker_pytorch_container.training:main","hosts":["algo-1","algo-2"],"hyperparameters":{},"input_config_dir":"/opt/ml/input/config","input_data_config":{},"input_dir":"/opt/ml/input","is_master":true,"job_name":"pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1/pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429/source/sourcedir.tar.gz","module_name":"train_pytorch_smdataparallel_mnist","network_interface_name":"eth0","num_cpus":64,"num_gpus":8,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"},"user_entry_point":"train_pytorch_smdataparallel_mnist.py"}
SM_USER_ARGS=[]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
PYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python36.zip:/opt/conda/lib/python3.6:/opt/conda/lib/python3.6/lib-dynload:/opt/conda/lib/python3.6/site-packages

Invoking script with the following command:

mpirun --host algo-1:8,algo-2:8 -np 16 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 2 -x NCCL_SOCKET_IFNAME=eth0 -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_HOMOGENEOUS=1 -x FI_PROVIDER=sockets -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so -x SMDATAPARALLEL_SERVER_ADDR=algo-1 -x SMDATAPARALLEL_SERVER_PORT=7592 -x SAGEMAKER_INSTANCE_TYPE=ml.p3.16xlarge smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py


2021-03-03 17:06:45,851 sagemaker-training-toolkit INFO     Process[es]: [psutil.Process(pid=49, name='orted', status='sleeping', started='17:06:45')]
2021-03-03 17:06:45,851 sagemaker-training-toolkit INFO     Orted process found [psutil.Process(pid=49, name='orted', status='sleeping', started='17:06:45')]
2021-03-03 17:06:45,851 sagemaker-training-toolkit INFO     Waiting for orted process [psutil.Process(pid=49, name='orted', status='sleeping', started='17:06:45')]
[1,0]<stdout>:NCCL version 2.7.8+cuda11.0
[1,8]<stdout>:NCCL version 2.7.8+cuda11.0
[1,0]<stdout>:Running smdistributed.dataparallel v1.0.0
[1,0]<stdout>:Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /tmp/data/MNIST/raw/train-images-idx3-ubyte.gz
[1,8]<stdout>:Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /tmp/data/MNIST/raw/train-images-idx3-ubyte.gz
[1,0]<stdout>:Traceback (most recent call last):
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,0]<stdout>:    "__main__", mod_spec)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,0]<stdout>:    exec(code, run_globals)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,0]<stdout>:    main()
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,0]<stdout>:    run_command_line(args)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,0]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,0]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 96, in _run_module_code
[1,0]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,0]<stdout>:    exec(code, run_globals)
[1,0]<stdout>:  File "train_pytorch_smdataparallel_mnist.py", line 173, in <module>
[1,0]<stdout>:    main()
[1,0]<stdout>:  File "train_pytorch_smdataparallel_mnist.py", line 126, in main
[1,0]<stdout>:    transforms.Normalize((0.1307,), (0.3081,))
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
[1,0]<stdout>:    self.download()
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 137, in download
[1,0]<stdout>:    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 235, in download_and_extract_archive
[1,0]<stdout>:    download_url(url, download_root, filename, md5)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 83, in download_url
[1,0]<stdout>:    raise e
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 71, in download_url
[1,0]<stdout>:    reporthook=gen_bar_updater()
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 248, in urlretrieve
[1,0]<stdout>:    with contextlib.closing(urlopen(url, data)) as fp:
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
[1,0]<stdout>:    return opener.open(url, data, timeout)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
[1,0]<stdout>:    response = meth(req, response)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
[1,0]<stdout>:    'http', request, response, code, msg, hdrs)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
[1,0]<stdout>:    return self._call_chain(*args)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
[1,0]<stdout>:    result = func(*args)
[1,0]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
[1,0]<stdout>:    raise HTTPError(req.full_url, code, msg, hdrs, fp)
[1,0]<stdout>:urllib.error.HTTPError: HTTP Error 403: Forbidden
[1,8]<stdout>:Traceback (most recent call last):
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,8]<stdout>:    "__main__", mod_spec)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,8]<stdout>:    exec(code, run_globals)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,8]<stdout>:    main()
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,8]<stdout>:    run_command_line(args)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,8]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,8]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 96, in _run_module_code
[1,8]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,8]<stdout>:    exec(code, run_globals)
[1,8]<stdout>:  File "train_pytorch_smdataparallel_mnist.py", line 173, in <module>
[1,8]<stdout>:    main()
[1,8]<stdout>:  File "train_pytorch_smdataparallel_mnist.py", line 126, in main
[1,8]<stdout>:    transforms.Normalize((0.1307,), (0.3081,))
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
[1,8]<stdout>:    self.download()
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 137, in download
[1,8]<stdout>:    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 235, in download_and_extract_archive
[1,8]<stdout>:    download_url(url, download_root, filename, md5)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 83, in download_url
[1,8]<stdout>:    raise e
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 71, in download_url
[1,8]<stdout>:    reporthook=gen_bar_updater()
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 248, in urlretrieve
[1,8]<stdout>:    with contextlib.closing(urlopen(url, data)) as fp:
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
[1,8]<stdout>:    return opener.open(url, data, timeout)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
[1,8]<stdout>:    response = meth(req, response)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
[1,8]<stdout>:    'http', request, response, code, msg, hdrs)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
[1,8]<stdout>:    return self._call_chain(*args)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
[1,8]<stdout>:    result = func(*args)
[1,8]<stdout>:  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
[1,8]<stdout>:    raise HTTPError(req.full_url, code, msg, hdrs, fp)
[1,8]<stdout>:urllib.error.HTTPError: HTTP Error 403: Forbidden
Warning: Permanently added 'algo-2,10.2.107.0' (ECDSA) to the list of known hosts.#015
[1,0]<stderr>:#0150it [00:00, ?it/s][1,8]<stderr>:#0150it [00:00, ?it/s]--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 5 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[algo-1:00040] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[algo-1:00040] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

2021-03-03 17:06:55,615 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
Command "mpirun --host algo-1:8,algo-2:8 -np 16 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 2 -x NCCL_SOCKET_IFNAME=eth0 -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_HOMOGENEOUS=1 -x FI_PROVIDER=sockets -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so -x SMDATAPARALLEL_SERVER_ADDR=algo-1 -x SMDATAPARALLEL_SERVER_PORT=7592 -x SAGEMAKER_INSTANCE_TYPE=ml.p3.16xlarge smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py"
Warning: Permanently added 'algo-2,10.2.107.0' (ECDSA) to the list of known hosts.#015
[1,0]<stderr>:#0150it [00:00, ?it/s][1,8]<stderr>:#0150it [00:00, ?it/s]--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 5 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[algo-1:00040] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[algo-1:00040] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
2021-03-03 17:06:55,617 sagemaker-training-toolkit INFO     Orted process exited

2021-03-03 17:07:09 Uploading - Uploading generated training model
2021-03-03 17:07:09 Failed - Training job failed
ProfilerReport-1614790795: Stopping
2021-03-03 17:07:25,648 sagemaker-training-toolkit INFO     MPI process finished.
2021-03-03 17:07:25,648 sagemaker-training-toolkit INFO     Reporting training SUCCESS
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-5-28be9b2c12b5> in <module>
----> 1 estimator.fit()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    662         self.jobs.append(self.latest_training_job)
    663         if wait:
--> 664             self.latest_training_job.wait(logs=logs)
    665 
    666     def _compilation_job_name(self):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1589         # If logs are requested, call logs_for_jobs.
   1590         if logs != "None":
-> 1591             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1592         else:
   1593             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3638 
   3639         if wait:
-> 3640             self._check_job_status(job_name, description, "TrainingJobStatus")
   3641             if dot:
   3642                 print()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   3220                 ),
   3221                 allowed_statuses=["Completed", "Stopped"],
-> 3222                 actual_status=status,
   3223             )
   3224 

UnexpectedStatusException: Error for Training job pytorch-smdataparallel-mnist-2021-03-03-16-59-55-429: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "mpirun --host algo-1:8,algo-2:8 -np 16 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 2 -x NCCL_SOCKET_IFNAME=eth0 -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_HOMOGENEOUS=1 -x FI_PROVIDER=sockets -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so -x SMDATAPARALLEL_SERVER_ADDR=algo-1 -x SMDATAPARALLEL_SERVER_PORT=7592 -x SAGEMAKER_INSTANCE_TYPE=ml.p3.16xlarge smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py"
Warning: Permanently added 'algo-2,10.2.107.0' (ECDSA) to the list of known hosts.
[1,0]<stderr>:
0it [00:00, ?it/s][1,8]<stderr>:
0it [00:00, ?it/s]--------------------------------------------------------------------------
MPI_ABOR
```

**To Reproduce**
Run all cells

**Comment by karan6181** [comment]
This has been fixed by https://github.com/aws/amazon-sagemaker-examples/pull/2056

**Comment by mchoi8739** [comment]
Downloaded the latest version, and confirm that it works end to end now. Thanks!
