### ISSUE TITLE
[Bug Report] AttributeError: 'bytes' object has no attribute 'read'

### ISSUE THREAD

**Issue by jonsnowseven** [aws/amazon-sagemaker-examples#2849]
**Link to the notebook**
[scikit_learn_randomforest example](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/scikit_learn_randomforest/Sklearn_on_SageMaker_end2end.ipynb)

**Describe the bug**
I am running the example end-2-end, **with sagemaker python SDK version 1.51.4**, and when predicting I get the following error:

```
Traceback (most recent call last):
  File "<masked>/.venv/lib/python3.7/site-packages/sagemaker/predictor.py", line 619, in __call__
    return np.load(BytesIO(stream.read()))
AttributeError: 'bytes' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    print(predictor.deserializer(ser))
  File "<masked>/.venv/lib/python3.7/site-packages/sagemaker/predictor.py", line 621, in __call__
    stream.close()
AttributeError: 'bytes' object has no attribute 'close'
```

**Comment by jonsnowseven** [comment]
Tried again and noticed there was a problem with my custom code. I was deploying an `SKLearnPredictor` with the wrong serializer/deserializer.

Sorry for any inconvenience. I'll close the issue.
