### ISSUE TITLE
[Bug Report]TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by zapaishchykova** [aws/amazon-sagemaker-examples#3126]
Hello!
Cannot run linters check from contributing guide: 
` tox -e black-format,black-nb-format`
 https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md,
I believe it's connected to the https://github.com/tomcatling/black-nb/issues/71

PC: macOs BigSur v 11.6.2

**Comment by jkroll-aws** [comment]
Can you please try `black-nb -l 100 {notebook-name}.ipynb`? 
If the issue is related to this latest version of black (22.1.0), can you try a downgrade? On my machine, I have black 21.11b1.

**Comment by zapaishchykova** [comment]
```
black-nb -l 100 causal-inference-container.ipynb 
Traceback (most recent call last):
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/bin/black-nb", line 8, in <module>
    sys.exit(cli())
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/annazp/anaconda3/envs/sagemaker-examples3/lib/python3.7/site-packages/black_nb/cli.py", line 200, in cli
    stdin_filename=stdin_filename,
  File "src/black/__init__.py", line 599, in get_sources
TypeError: 'NoneType' object is not subscriptable

```

**Comment by zapaishchykova** [comment]
i have tried to update tox.ini to following:
```
# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = black-format,black-check,black-nb-check,black-nb-format
skipsdist=True

[testenv:black-format]
setenv =
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
deps = black
commands =
    black -l 100 ./

[testenv:black-check]
setenv =
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
deps = black
commands =
    black -l 100 --check ./

[testenv:black-nb-check]
deps = black-nb
commands =
    black-nb -l 100 --check ./

[testenv:black-nb-format]
deps = black-nb
commands =
    black-nb -l 100 ./

```
I get the following:
```
All done! ✨ 🍰 ✨
52 files reformatted, 411 files left unchanged, 5 files failed to reformat.
ERROR: InvocationError for command /Users/annazp/amazon-sagemaker-examples/.tox/black-nb-format/bin/black-nb -l 100 ./ (exited with code 123)
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
  black-format: commands succeeded
ERROR:   black-nb-format: commands failed

```

**Comment by zapaishchykova** [comment]
If i just downgrade with `pip install black==21.11b1`
And then run :
`black-nb -l 100 causal-inference-container.ipynb`
I get:
   ```
 14 cells left unchanged, 1 cell failed to reformat.
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Comment by jkroll-aws** [comment]
That output looks good with the `black==21.11b1`. There are occasional failures to reformat a cell or two. The formatting check may fail, but I think this is sufficient. Looks like this is an issue with the latest black verison, good find.
