### ISSUE TITLE
Error installing python libraries in Studio

### ISSUE THREAD

**Issue by C24IO** [aws/amazon-sagemaker-examples#948]
https://github.com/awslabs/amazon-sagemaker-examples/blob/ba0b6ee30fee94968b2c0dc85145c88e4a70ff7b/aws_sagemaker_studio/sagemaker_experiments/mnist-handwritten-digits-classification-experiment.ipynb#L63

!
!sudo {sys.executable} -m pip install torch
!sudo {sys.executable} -m pip install torchvision
!pip install torchvision
Collecting torch
SystemError: deallocated bytearray object has exported buffers
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 525, in _download_http_url
    stream=True,
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/session.py", line 426, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 136, in unpackb
    ret = unpacker._unpack()
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 617, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 460, in _read_header
    obj = self._read(n)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 370, in _read
    return self._buffer[i:i+n]
MemoryError
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/74/ee/d872c12ea508f9cca4cf0d7b91fc5a5e476cec77628a66795ec5a585a67f/torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from torchvision) (1.13.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from torchvision) (1.17.3)
Requirement already satisfied: pillow>=4.1.1 in /opt/conda/lib/python3.7/site-packages (from torchvision) (6.2.1)
Collecting torch==1.3.1
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 525, in _download_http_url
    stream=True,
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/session.py", line 426, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 136, in unpackb
    ret = unpacker._unpack()
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 617, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 460, in _read_header
    obj = self._read(n)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 370, in _read
    return self._buffer[i:i+n]
MemoryError
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/74/ee/d872c12ea508f9cca4cf0d7b91fc5a5e476cec77628a66795ec5a585a67f/torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from torchvision) (1.13.0)
Collecting torch==1.3.1
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/download.py", line 525, in _download_http_url
    stream=True,
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/session.py", line 426, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 136, in unpackb
    ret = unpacker._unpack()
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 659, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 617, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 460, in _read_header
    obj = self._read(n)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 370, in _read
    return self._buffer[i:i+n]
MemoryError

**Comment by jaipreet-s** [comment]
Hi @C24IO ,

I just confirmed that on the latest Data Science kernel that all the packages in the notebook can be successfully installed.  Could you please try again with the latest kernel? Thanks for using SageMaker Studio!

[
![Screen Shot 2020-01-03 at 11 56 08 AM](https://user-images.githubusercontent.com/43826141/71745798-0ff88d80-2e20-11ea-989f-d1357b3482d3.png)
](url)

**Comment by danabens** [comment]
wasn't able to repro using 3.7.3, @C24IO can you still reprooduce?

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-experiments/mnist-handwritten-digits-classification-experiment/mnist-handwritten-digits-classification-experiment.ipynb

**Comment by danabens** [comment]
Issue out of date - I was able to run the notebook in studio with the latest data science kernel. Please create a new issue if issue persists.

**Comment by radhikachoudhary64** [comment]
i m facing this error .Please help
