### ISSUE TITLE
Saving a pipeline with customized transformer

### ISSUE THREAD

**Issue by songyuzhou324** [aws/amazon-sagemaker-examples#984]
I'm following this tutorial and creating a data process pipeline with a customized transformer named "processText". The pipeline works well but got error during saving:

Traceback (most recent call last):
  File "script_2020-01-14-23-57-02.py", line 190, in <module>
    main()
  File "script_2020-01-14-23-57-02.py", line 170, in main
    SimpleSparkSerializer().serializeToBundle(model, "jar:file:/tmp/model.zip", validation_df)
  File "/mnt/yarn/usercache/root/appcache/application_1579044435711_0001/container_1579044435711_0001_01_000001/python.zip/mleap/pyspark/spark_support.py", line 42, in serializeToBundle
  File "/mnt/yarn/usercache/root/appcache/application_1579044435711_0001/container_1579044435711_0001_01_000001/pyspark.zip/pyspark/ml/pipeline.py", line 316, in _to_java
AttributeError: 'processText' object has no attribute '_to_java'

Can anyone help me on this? In real world, customized transformer is usually needed, so an example showing how to work with customized transformer will be very valuable.

Thanks

**Comment by songyuzhou324** [comment]
Previously i also encountered issue when saving/re-loading a customized transformer in pyspark.

**Comment by hsl89** [comment]
hi @songyuzhou324 , can you provide the link to the notebook?

**Comment by hsl89** [comment]
close for lack of activity
